# Generated by Django 4.2.2 on 2023-06-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Credenciado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cnpj", models.CharField(blank=True, max_length=18, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("telefone", models.CharField(blank=True, max_length=80, null=True)),
                ("endereco", models.CharField(blank=True, max_length=150, null=True)),
                ("cidade", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "uf",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AC", "AC"),
                            ("AL", "AL"),
                            ("AP", "AP"),
                            ("AM", "AM"),
                            ("BA", "BA"),
                            ("CE", "CE"),
                            ("DF", "DF"),
                            ("ES", "ES"),
                            ("GO", "GO"),
                            ("MA", "MA"),
                            ("MT", "MT"),
                            ("MS", "MS"),
                            ("MG", "MG"),
                            ("PA", "PA"),
                            ("PB", "PB"),
                            ("PR", "PR"),
                            ("PE", "PE"),
                            ("PI", "PI"),
                            ("RJ", "RJ"),
                            ("RN", "RN"),
                            ("RS", "RS"),
                            ("RO", "RO"),
                            ("RR", "RR"),
                            ("SC", "SC"),
                            ("SP", "SP"),
                            ("SE", "SE"),
                            ("TO", "TO"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("servicos", models.TextField(blank=True, null=True)),
                ("observacao", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
