version: '3.9'

services:
  web:
    container_name: django_credenciados
    build:
      context: .
    command: commands.sh
    expose:
      - "8000"
    volumes:
      - ./scripts:/var/django/scripts
    env_file:
      - ./.env-prod
    depends_on:
      - psql

  nginx:
    container_name: nginx_credenciados
    build:
      context: ./nginx/
    restart: always
    volumes:
      - ./static/:/var/django/static
      - ./media/:/var/django/media
    ports:
      - "80:80"
    depends_on:
      - web

  psql:
    container_name: psql_credenciados
    image: postgres:15-bookworm
    volumes:
      - /var/postgresql/data:/var/lib/postgresql/data/
    env_file:
      - ./.env-psql
