version: "3.9"

services:
  web:
    container_name: django
    build:
      context: .
    command: gunicorn --bind 0.0.0.0:8000 core.wsgi --workers=4
    restart: always
    volumes:
      - ./django_credenciados/:/var/django/
    expose:
      - "8000"
    env_file:
      - ./config/.env-dev
    networks:
      - net_dev_nginx

  nginx:
    container_name: nginx
    build:
      context: ./nginx/
    restart: always
    volumes:
      - ./django_credenciados/static/:/var/django/static
      - ./django_credenciados/media/:/var/django/media
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - net_dev_nginx

networks:
  net_dev_nginx:
