name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, 3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./django_credenciados/requirements.txt
    - name: Run Tests
      env:
        SECRET_KEY: "django-insecure-1!()yal53=@&g=j2wfz5m7*)a7yc41u91ii#ki45zjvrvla((8"
        DEBUG: "True"
        DB_ENGINE: "django.db.backends.sqlite3"
        POSTGRES_DB: "db.sqlite3"
        POSTGRES_USER: "None"
        POSTGRES_PASSWORD: "None"
        POSTGRES_HOST: "None"
        POSTGRES_PORT: "None"
      run: |
        python ./django_credenciados/manage.py test
